### PR TITLE
160 Support Websocket API requests

### PR DESCRIPTION
**Pull request by suceava**
to address issue #160
https://github.com/dbartholomae/middy-middleware-jwt-auth/issues/160

### CODE REVIEW

**Comment by dbartholomae** [comment]
Thanks! Please rebase with commit messages using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/). These will be used automatically to generate the changelog. I would suggest `feat: support Websocket API requests`.

**Comment by suceava** [comment]
Not sure what to do about the CLA signature, the link in that comment seems to be broken

**Comment by dbartholomae** [comment]
What is the problem you run into there? For me, it is working in different (anonymous) browser windows.

**Review by dbartholomae — APPROVED** [review]
Nice! :)

**Comment by suceava** [comment]
The page wasn't loading, it was throwing a 400 error ... It worked this time though 🤷

**Comment by dbartholomae** [comment]
Thanks! It's a free tool, maybe it's running into some limits. I'll keep an eye on it :)

**Pull request merged**
